version: '3.9'

services:
  mysqldb:
    image: mysql:8.0
    #container_name: sharebook-mysqldb
    restart: unless-stopped
    env_file: ./.env  # Charge toutes les variables depuis .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql  # Persistance des données
    command: --default-authentication-plugin=mysql_native_password

  app:
    #container_name: sharebook-app
    build: .
    depends_on:
        - mysqldb
    restart: on-failure
    env_file: ./.env
    environment:
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_DATABASE_PLATFORM=${SPRING_JPA_DATABASE_PLATFORM}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    volumes:
      - .m2:/root/.m2

volumes:
  mysql_data:
